#Defines how groups will be sorted in symbol selection overlay.
#Undefined groups will be sorted alphabetically and placed after defined ones.
symbol_selection_groups_sorting = ["primary", "symbols", "tools"]
#Contents of the Chalk Box will be shown in item's tooltip.
chalk_box_tooltip_contents = true
#Information about using Chalk Box will be shown in the item's tooltip.
chalk_box_tooltip_details = true
