[update]
	skipUpdate = "1.5.4"

[permission]
	#Is creative mode required?
	requireCreative = false
	#Require easy_mob_spawn_control.admin permission (Forge Permission API).
	requireAdmin = true
	#Vanilla permission level required to use the mod.0 - All players, 1 - Moderator, 2 - GameMaster, 3 - Admin, 4 - OP
	# Default: 2
	# Range: 0 ~ 4
	permissionLevel = 2

[misc]
	#Decrease this value to make creatures spawn faster. Or increase for opposite effect.
	#-1 = default value (400 ticks).
	# Default: -1
	# Range: -1 ~ 4000
	creatureNaturalSpawnCheckTicks = -1
	#Minimum spacing between mobs when spawning.
	#-1 = disabled.
	# Default: -1
	# Range: -1 ~ 512
	sparseMobRange = -1
	#Should SPARSE_MOB_RANGE affect monsters?
	sparse_mob_affect_monsters = true
	#Should SPARSE_MOB_RANGE affect animals?
	sparse_mob_affect_animals = true
