#Whether to use the player's Luck attribute when rolling for Tiers (defaults to a Luck value of 1 if disabled)
use_vanilla_luck = true
#A global multiplier for all Tier rolls
# Default: 1.0
# Range: -2.147483647E9 ~ 2.147483647E9
luck_multiplier = 1.0
#XP cost multiplier for Ascending Tiers
# Default: 1.0
# Range: 0.1 ~ 100.0
ascend_xp_cost_multiplier = 1.0
