#Enable tracking pointer
Available = false
#Scale of cursor
# Default: 0.6
# Range: 0.01 ~ 4.0
Scale = 0.6
#Max tracking quantity
# Default: 10
# Range: 1 ~ 400
"Max quantity" = 10
#Interval between world position refresh
# Default: 1
# Range: 1 ~ 160
Interval = 1
#Enable center relative icon display
"Center relative available" = true
#The algorithm of center rela projection
#Allowed Values: MERCATOR, AITOFF, WINKEL_TRIPLE
"Project algorithm" = "AITOFF"
#Enable full track icon display
"Track full available" = false
#Enable longitude icon display
"Head flat available" = false
#List of entity types with cursors for center relative display, separated with "|"
"EntityType|PointerIconType|EntityIconType(|OptionalValue)" = ["minecraft:ender_dragon|normal|ender_dragon_head", "minecraft:wither|normal_white|wither_head", "terra_entity:king_slime|normal|king_slime", "terra_entity:eye_of_cthulhu|normal|eye_of_cthulhu", "terra_entity:brain_of_cthulhu|normal|brain_of_cthulhu", "terra_entity:eater_of_worlds|normal|eater_of_worlds", "terra_entity:queen_bee|normal|queen_bee", "terra_entity:deerclops|normal|deerclops", "terra_entity:skeletron|normal|skeletron", "terra_entity:hill_of_flesh|normal|wall_of_flesh", "terra_entity:wall_of_flesh|normal|wall_of_flesh", "terra_entity:demon_eye|normal|none", "terra_entity:flying_fish|normal|none", "terra_entity:crimera|normal|none", "terra_entity:eater_of_souls|normal|none", "terra_entity:giant_worm|normal|none", "terra_entity:tomb_crawler|normal|none", "terra_entity:devourer|normal|none", "terra_entity:cave_bat|normal|none", "terra_entity:jungle_bat|normal|none", "terra_entity:snatcher|normal|none", "terra_entity:man_eater|normal|none", "terra_entity:hornet|normal|none", "terra_entity:hell_bat|normal|none", "terra_entity:ice_bat|normal|none", "terra_entity:spore_bat|normal|none", "terra_entity:harpy|normal|none", "terra_entity:cursed_skull|normal|none", "terra_entity:dark_caster|normal|none", "terra_entity:antlion_swarmer|normal|none", "terra_entity:giant_antlion_swarmer|normal|none", "terra_entity:wyvern|normal|none", "terra_entity:granite_elemental|normal|none", "terra_entity:ghost|normal|none", "terra_entity:fire_imp|normal|none", "terra_entity:demon|normal|none", "terra_entity:voodoo_demon|normal|none", "terra_entity:bone_serpent|normal|none", "terra_entity:wither_bone_serpent|normal|none", "terra_entity:meteor_head|normal|none"]
#List of entity types with cursors for full track display, separated with "|"
"entityType|type:icon(|optionalPattern)" = ["minecraft:wither|normal:point_x"]
