#Client-only settings
[client]
	#If true, the currently held item will be swapped with the selected tool belt slot when closing the tool belt GUI
	swapOnClose = true
	#Displays the full tooltip when hovering over an item in the tool belt. If false, only the item name is shown
	showTooltip = false
	#Overlay opacity
	# Default: 0.75
	# Range: 0.0 ~ 1.0
	opacity = 0.75
	#Overlay X offset (positive value moves right, negative moves left)
	# Default: 0
	# Range: > -2147483648
	offsetX = 0
	#Overlay Y offset (positive value moves down, negative moves up)
	# Default: 0
	# Range: > -2147483648
	offsetY = 0
	#If true, the tool belt GUI will open only while the player holds the keybind. Otherwise, a single press will toggle the GUI
	holdToOpen = true
