#===========[ Loot Journal Client Config ]===========
# Please prefer editing the config through the in-game 
# configuration screen (available via the mods list),
# as it includes many hints and quality-of-life improvements.
#====================================================
enableLootJournal = true
showItemPickups = true
showXpPickups = true
showOverflowPickups = true
abbreviateNumbers = true
#Allowed Values: TYPE_NAMED, TYPE, STRICT, NONE
mergeMode = "TYPE_NAMED"
#Allowed Values: FIXED_SLOTS, SMOOTH_FLOW
stackingMode = "SMOOTH_FLOW"
# Default: 100
# Range: 0 ~ 500
maxNameWidth = 100
# Default: 4.0
# Range: 1.0 ~ 60.0
displayTime = 4.0
# Default: 9
# Range: 1 ~ 64
displayCapacity = 9
# Default: 9
# Range: 0 ~ 256
queueSize = 9
activeTheme = "Classic"
#Allowed Values: TOP_LEFT, TOP_RIGHT, BOTTOM_LEFT, BOTTOM_RIGHT
screenAnchor = "BOTTOM_RIGHT"
#Allowed Values: NATURAL, UP, DOWN
growthDirection = "NATURAL"
# Default: 0
# Range: -256 ~ 256
anchorXOffset = 0
# Default: 32
# Range: -256 ~ 256
anchorYOffset = 32
# Default: 2
# Range: 0 ~ 16
separation = 2
# Default: 1.0
# Range: 0.1 ~ 3.0
scale = 1.0
elementOrder = "COUNT 4px NAME 4px ICON 4px TOTAL"
# Default: 0
# Range: 0 ~ 32
elementPaddingLeft = 0
# Default: 0
# Range: 0 ~ 32
elementPaddingRight = 0
# Default: 0
# Range: 0 ~ 16
elementPaddingTop = 0
# Default: 0
# Range: 0 ~ 16
elementPaddingBottom = 0
# Default: 0.8
# Range: 0.0 ~ 5.0
fadeInTime = 0.8
# Default: 1.0
# Range: 0.0 ~ 5.0
fadeOutTime = 1.0
#Allowed Values: LINEAR, CEIL, FLOOR, EASE_IN_SINE, EASE_IN_CIRCLE, EASE_IN_QUAD, EASE_IN_CUBIC, EASE_IN_QUART, EASE_IN_QUINT, EASE_IN_EXPO, EASE_IN_BACK, EASE_IN_ELASTIC, EASE_IN_BOUNCE, EASE_OUT_SINE, EASE_OUT_CIRCLE, EASE_OUT_QUAD, EASE_OUT_CUBIC, EASE_OUT_QUART, EASE_OUT_QUINT, EASE_OUT_EXPO, EASE_OUT_BACK, EASE_OUT_ELASTIC, EASE_OUT_BOUNCE, EASE_IN_OUT_SINE, EASE_IN_OUT_CIRCLE, EASE_IN_OUT_QUAD, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUART, EASE_IN_OUT_QUINT, EASE_IN_OUT_EXPO, EASE_IN_OUT_BACK, EASE_IN_OUT_ELASTIC, EASE_IN_OUT_BOUNCE, EASE_OUT_IN_SINE, EASE_OUT_IN_CIRCLE, EASE_OUT_IN_QUAD, EASE_OUT_IN_CUBIC, EASE_OUT_IN_QUART, EASE_OUT_IN_QUINT, EASE_OUT_IN_EXPO, EASE_OUT_IN_BACK, EASE_OUT_IN_ELASTIC, EASE_OUT_IN_BOUNCE
fadeInEasing = "EASE_OUT_BACK"
#Allowed Values: LINEAR, CEIL, FLOOR, EASE_IN_SINE, EASE_IN_CIRCLE, EASE_IN_QUAD, EASE_IN_CUBIC, EASE_IN_QUART, EASE_IN_QUINT, EASE_IN_EXPO, EASE_IN_BACK, EASE_IN_ELASTIC, EASE_IN_BOUNCE, EASE_OUT_SINE, EASE_OUT_CIRCLE, EASE_OUT_QUAD, EASE_OUT_CUBIC, EASE_OUT_QUART, EASE_OUT_QUINT, EASE_OUT_EXPO, EASE_OUT_BACK, EASE_OUT_ELASTIC, EASE_OUT_BOUNCE, EASE_IN_OUT_SINE, EASE_IN_OUT_CIRCLE, EASE_IN_OUT_QUAD, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUART, EASE_IN_OUT_QUINT, EASE_IN_OUT_EXPO, EASE_IN_OUT_BACK, EASE_IN_OUT_ELASTIC, EASE_IN_OUT_BOUNCE, EASE_OUT_IN_SINE, EASE_OUT_IN_CIRCLE, EASE_OUT_IN_QUAD, EASE_OUT_IN_CUBIC, EASE_OUT_IN_QUART, EASE_OUT_IN_QUINT, EASE_OUT_IN_EXPO, EASE_OUT_IN_BACK, EASE_OUT_IN_ELASTIC, EASE_OUT_IN_BOUNCE
fadeOutEasing = "EASE_IN_CUBIC"
# Default: 1.0
# Range: 0.0 ~ 10.0
pulseStrength = 1.0
# Default: 0.5
# Range: 0.0 ~ 5.0
pulseTime = 0.5
# Default: 0.1
# Range: 0.0 ~ 1.0
pulsePeak = 0.1
#Allowed Values: LINEAR, CEIL, FLOOR, EASE_IN_SINE, EASE_IN_CIRCLE, EASE_IN_QUAD, EASE_IN_CUBIC, EASE_IN_QUART, EASE_IN_QUINT, EASE_IN_EXPO, EASE_IN_BACK, EASE_IN_ELASTIC, EASE_IN_BOUNCE, EASE_OUT_SINE, EASE_OUT_CIRCLE, EASE_OUT_QUAD, EASE_OUT_CUBIC, EASE_OUT_QUART, EASE_OUT_QUINT, EASE_OUT_EXPO, EASE_OUT_BACK, EASE_OUT_ELASTIC, EASE_OUT_BOUNCE, EASE_IN_OUT_SINE, EASE_IN_OUT_CIRCLE, EASE_IN_OUT_QUAD, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUART, EASE_IN_OUT_QUINT, EASE_IN_OUT_EXPO, EASE_IN_OUT_BACK, EASE_IN_OUT_ELASTIC, EASE_IN_OUT_BOUNCE, EASE_OUT_IN_SINE, EASE_OUT_IN_CIRCLE, EASE_OUT_IN_QUAD, EASE_OUT_IN_CUBIC, EASE_OUT_IN_QUART, EASE_OUT_IN_QUINT, EASE_OUT_IN_EXPO, EASE_OUT_IN_BACK, EASE_OUT_IN_ELASTIC, EASE_OUT_IN_BOUNCE
pulseEaseIn = "EASE_OUT_CUBIC"
#Allowed Values: LINEAR, CEIL, FLOOR, EASE_IN_SINE, EASE_IN_CIRCLE, EASE_IN_QUAD, EASE_IN_CUBIC, EASE_IN_QUART, EASE_IN_QUINT, EASE_IN_EXPO, EASE_IN_BACK, EASE_IN_ELASTIC, EASE_IN_BOUNCE, EASE_OUT_SINE, EASE_OUT_CIRCLE, EASE_OUT_QUAD, EASE_OUT_CUBIC, EASE_OUT_QUART, EASE_OUT_QUINT, EASE_OUT_EXPO, EASE_OUT_BACK, EASE_OUT_ELASTIC, EASE_OUT_BOUNCE, EASE_IN_OUT_SINE, EASE_IN_OUT_CIRCLE, EASE_IN_OUT_QUAD, EASE_IN_OUT_CUBIC, EASE_IN_OUT_QUART, EASE_IN_OUT_QUINT, EASE_IN_OUT_EXPO, EASE_IN_OUT_BACK, EASE_IN_OUT_ELASTIC, EASE_IN_OUT_BOUNCE, EASE_OUT_IN_SINE, EASE_OUT_IN_CIRCLE, EASE_OUT_IN_QUAD, EASE_OUT_IN_CUBIC, EASE_OUT_IN_QUART, EASE_OUT_IN_QUINT, EASE_OUT_IN_EXPO, EASE_OUT_IN_BACK, EASE_OUT_IN_ELASTIC, EASE_OUT_IN_BOUNCE
pulseEaseOut = "EASE_OUT_ELASTIC"
enableRayGlow = true
trackItemPickups = false
trackXpPickups = false
enablePlayerFiltering = false
playerWhitelist = []
enableSounds = true
soundId = "minecraft:entity.item.pickup"
# Default: 1.0
# Range: 0.0 ~ 1.0
soundVolume = 1.0
# Default: 1.0
# Range: 0.0 ~ 2.0
soundPitch = 1.0
enableFiltering = false
hideYourCommonItems = false
hideOtherCommonItems = false
#Allowed Values: ALLOW_ALL, DENY_ALL
defaultFilterRule = "ALLOW_ALL"
itemIdBlacklist = []
itemIdWhitelist = []
itemTagBlacklist = []
itemTagWhitelist = []
modIdBlacklist = []
modIdWhitelist = []
